### ISSUE TITLE
How to get 'Earn' value from wallet?

### ISSUE THREAD

**Issue by bonoirk** [shammysha/homeassistant-binance-pool#19]
Hello and thanks for component. Is it possible to get "earn" value from wallet?
![earn](https://user-images.githubusercontent.com/73544496/162921263-ab9e5751-9277-4392-9047-a0280305c9de.png)

**Comment by shammysha** [comment]
Binance API allow get savings balance in BTC and USDT coins.
Please check new version 1.4.1

New sensors added with names? like **<domain>_<coin>_savings**
