### ISSUE TITLE
HA stuck with default settings 

### ISSUE THREAD

**Issue by Antexa** [shammysha/homeassistant-binance-pool#22]
I notice that when I go with the only required settings and some specifics (domain, native currency and name), my HA instance is stuck, the only way to start HA is to go back with the settings you mention in the read me and perform a reboot of the host. 

```binance_pool:
  name: Binance
  domain: com
  api_key: redacted
  api_secret: redacted
  native_currency: 
    - EUR
```

Host details : 

## System Health

version | core-2022.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4892
Installed Version | 1.24.5
Stage | running
Available Repositories | 1092
Downloaded Repositories | 19

</details>

**Comment by shammysha** [comment]
Hello.
If You omit "balances" in configuration, component will create sensor foreach coin, that can be operated on Binance (3120 (!)) 

It's not good idea

**Comment by Antexa** [comment]
My bad, the readme mention : 
`a sensor will be created for every coin that Binance offers (54 unique coins/currencies from Binance.us at this time)`

` By default (without adding this key), a sensor will be created for every exchange pair that Binance offers (109 pairs from Binance.us at this time). ` 

Same thing should happens for exchanges too ?

I try to add SOLANA token, but with no luck and it's time consuming because HA crash each time and I need to restart the host by unplug/plug power

**Comment by shammysha** [comment]
You're right.
Without "exchanges" in config - You get sensors for each available asset.
When I talk about 3152 sensors - it's total sensors for bundles (balances + exchanges)

> I try to add SOLANA token

Please use short name "SOL", not "SOLANA"

This config work:

```
binance_pool:
  domain: com
  name: Binance
  native_currency:
    - EUR
  api_key: !secret binance_api
  api_secret: !secret binance_secret
  balances:
    - SOL
  exchanges:
    - SOLEUR
```

**Comment by Antexa** [comment]
Ok it works, I don't really understand what was the problem.
