### ISSUE TITLE
Help. Sensors unavailable

### ISSUE THREAD

**Issue by AndreySupr** [shammysha/homeassistant-binance-pool#35]
Help, all sensors are constantly falling into unavailable. How to fix the timeout yourself?
![Снимок](https://user-images.githubusercontent.com/79106509/195152358-a77d1a82-05ca-465a-88b4-69351d39bfc5.PNG)

Error requesting BinanceDataWallet data: Cannot connect to host api.binance.com:443 ssl:default [Try again]
Timeout fetching BinanceDataWallet data
Error requesting BinanceDataWallet data: Cannot connect to host api.binance.com:443 ssl:default [Connection reset by peer]

upd:  **packets are not lost in the console**

64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=400 ttl=63 time=148 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=401 ttl=63 time=144 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=402 ttl=63 time=312 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=403 ttl=63 time=146 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=404 ttl=63 time=131 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=405 ttl=63 time=115 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=406 ttl=63 time=140 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=407 ttl=63 time=169 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=408 ttl=63 time=258 ms
64 bytes from server-108-157-231-147.arn56.r.cloudfront.net (108.157.231.147): icmp_seq=409 ttl=63 time=181 ms

**Comment by shammysha** [comment]
I think, It was temporaly problems with response on Binance side. 
I don't think, that timeout option will resolve problems, issued by 3rd party, because for any value in timeout - they'll found greater :)
