### ISSUE TITLE
Is it possible to get FUNDING_WALLET value from Binance?

### ISSUE THREAD

**Issue by bonoirk** [shammysha/homeassistant-binance-pool#5]
Hello! Thanks for great component!
Is it possible to get FUNDING_WALLET value from Binance? As I can see, btc_balance sensor gets SPOT_WALLET value only.

**Comment by shammysha** [comment]
Please, check last release (1.2.23)
Sensors "<domain> <coin> funding" for each coin listed in "balances" item (configuration)
